export const dataDummy = [
  {
    id: 0,
    image: require('../images/propertyImage2.jpg'),
    title: '3 Bed, 2 Bath, 3450 square Ft',
    description: `To the left is the modern kitchen with central island, leading through to the unique breakfast family room which feature glass walls and doors out onto the garden and access to the separate utility room.`,
    price: 40000000,
    status: 'Rent',
    type: 'General',
    size: 3450,
    address: '3, Belmont Gardens',
    state: 'Lagos',
    city: 'Lekki phase 1',
    view: 20,
    likes: 206,
    neighbourhood: 'Lekki Phase I',
    user: 'user',
    userId: '123EFT',
    bathrooms: 3,
    bedrooms: 3,
    availability: true,
    amenities: [
      {id: 0, number: 1, amenity: 'EquippedKitchen'},
      {id: 1, number: 1, amenity: 'Pool'},
      {id: 2, number: 1, amenity: 'Amenity.Laundry'},
      {id: 3, number: 1, amenity: 'Amenity.Electricity'},
    ],
  },
  {
    id: 0,
    image: require('../images/propertyImage2.jpg'),
    title: '3 Bed, 2 Bath, 3450 square Ft',
    description: `To the left is the modern kitchen with central island, leading through to the unique breakfast family room which feature glass walls and doors out onto the garden and access to the separate utility room.`,
    price: 40000000,
    status: 'Rent',
    type: 'General',
    size: 3450,
    address: '3, Belmont Gardens',
    state: 'Lagos',
    city: 'Lekki phase 1',
    view: 20,
    likes: 206,
    neighbourhood: 'Lekki Phase I',
    user: 'user',
    userId: '123EFT',
    bathrooms: 3,
    bedrooms: 3,
    availability: true,
    amenities: [
      {id: 0, number: 1, amenity: 'EquippedKitchen'},
      {id: 1, number: 1, amenity: 'Pool'},
      {id: 2, number: 1, amenity: 'Amenity.Laundry'},
      {id: 3, number: 1, amenity: 'Amenity.Electricity'},
    ],
  },
  {
    id: 0,
    image: require('../images/propertyImage2.jpg'),
    title: '3 Bed, 2 Bath, 3450 square Ft',
    description: `To the left is the modern kitchen with central island, leading through to the unique breakfast family room which feature glass walls and doors out onto the garden and access to the separate utility room.`,
    price: 40000000,
    status: 'Rent',
    type: 'General',
    size: 3450,
    address: '3, Belmont Gardens',
    state: 'Lagos',
    city: 'Lekki phase 1',
    view: 20,
    likes: 206,
    neighbourhood: 'Lekki Phase I',
    user: 'user',
    userId: '123EFT',
    bathrooms: 3,
    bedrooms: 3,
    availability: true,
    amenities: [
      {id: 0, number: 1, amenity: 'EquippedKitchen'},
      {id: 1, number: 1, amenity: 'Pool'},
      {id: 2, number: 1, amenity: 'Amenity.Laundry'},
      {id: 3, number: 1, amenity: 'Amenity.Electricity'},
    ],
  },
  {
    id: 0,
    image: require('../images/propertyImage2.jpg'),
    title: '3 Bed, 2 Bath, 3450 square Ft',
    description: `To the left is the modern kitchen with central island, leading through to the unique breakfast family room which feature glass walls and doors out onto the garden and access to the separate utility room.`,
    price: 40000000,
    status: 'Rent',
    type: 'General',
    size: 3450,
    address: '3, Belmont Gardens',
    state: 'Lagos',
    city: 'Lekki phase 1',
    view: 20,
    likes: 206,
    neighbourhood: 'Lekki Phase I',
    user: 'user',
    userId: '123EFT',
    bathrooms: 3,
    bedrooms: 3,
    availability: true,
    amenities: [
      {id: 0, number: 1, amenity: 'EquippedKitchen'},
      {id: 1, number: 1, amenity: 'Pool'},
      {id: 2, number: 1, amenity: 'Amenity.Laundry'},
      {id: 3, number: 1, amenity: 'Amenity.Electricity'},
    ],
  },
];
